services:
  open-deep-research-platform-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    image: open-deep-research-platform-web
    ports:
      - "3000:3000"
    env_file:
      - .env
